ADMIN_USERS = [
    "alexandra.gradinaru@nordcloud.com",
    "alexandru.anghel@nordcloud.com",
    "antonia.olaru@nordcloud.com",
    "grzegorz.prokopczyk@nordcloud.com",
    "jan.kaczmarek@nordcloud.com",
    "maciej.wilczynski@nordcloud.com",
    "mateusz.schoen@nordcloud.com",
    "mihai.giol@nordcloud.com",
    "mikolaj.kaczmarek@nordcloud.com",
    "mikolaj.matuszny@nordcloud.com",
    "patryk.wieczorek@nordcloud.com",
    "pawel.dzwonkowski@nordcloud.com",
    "robert.kubis@nordcloud.com",
    "datadog@nordcloud.com",
    "mc-terraform-dd@nordcloud.com",
    "mc-terraform-dd-dev@nordcloud.com",
]
